#!/usr/bin/env node

/**
 * Script para garantir que o Prisma Client seja gerado corretamente antes do build
 * Executa o Prisma generate e cria arquivos faltantes se necessário
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const projectRoot = path.join(__dirname, "..");
const generatedPrismaPath = path.join(projectRoot, "src", "generated", "prisma");
const enumsFile = path.join(generatedPrismaPath, "enums.ts");
const clientFile = path.join(generatedPrismaPath, "client.ts");
const schemaPath = path.join(projectRoot, "prisma", "schema.prisma");

console.log("Garantindo que o Prisma Client seja gerado...");

// Limpar o diretório gerado para garantir que não há arquivos antigos com Data Proxy
if (fs.existsSync(generatedPrismaPath)) {
  console.log("Limpando diretório gerado anteriormente para evitar conflitos...");
  try {
    fs.rmSync(generatedPrismaPath, { recursive: true, force: true });
  } catch (error) {
    console.warn("⚠ Não foi possível limpar o diretório:", error.message);
  }
}

// Garantir que o diretório existe
if (!fs.existsSync(generatedPrismaPath)) {
  console.log("Criando diretório:", generatedPrismaPath);
  fs.mkdirSync(generatedPrismaPath, { recursive: true });
}

// Executar Prisma generate explicitamente SEM Data Proxy
console.log("Executando: npx prisma generate (sem Data Proxy)");
try {
  // Garantir que o Data Proxy está desabilitado e limpar variáveis relacionadas
  const env = {
    ...process.env,
    PRISMA_GENERATE_DATAPROXY: "false",
    PRISMA_CLIENT_ENGINE_TYPE: "library",
  };
  
  // Remover qualquer variável que possa forçar o Data Proxy
  delete env.PRISMA_CLI_QUERY_ENGINE_TYPE;
  delete env.PRISMA_CLIENT_DATAPROXY_URL;
  delete env.DATAPROXY_URL;
  
  // Garantir que DATABASE_URL está definida e não é do Data Proxy
  if (env.DATABASE_URL && (env.DATABASE_URL.startsWith("prisma://") || env.DATABASE_URL.startsWith("prisma+"))) {
    console.error("❌ DATABASE_URL está configurada para usar Prisma Data Proxy!");
    console.error("Configure DATABASE_URL com uma string de conexão MongoDB direta (ex: mongodb+srv://...)");
    process.exit(1);
  }
  
  execSync("npx prisma generate", {
    cwd: projectRoot,
    stdio: "inherit",
    env: env,
  });
  console.log("✓ Prisma generate executado com sucesso (sem Data Proxy)");
} catch (error) {
  console.error("⚠ Erro ao executar prisma generate:", error.message);
  // Continuar mesmo se houver erro, vamos criar os arquivos manualmente
}

// Verificar se os arquivos foram gerados
const clientExists = fs.existsSync(clientFile);
const enumsExists = fs.existsSync(enumsFile);

// Verificar se o client.ts gerado não está usando Data Proxy
if (clientExists) {
  try {
    const clientContent = fs.readFileSync(clientFile, "utf8");
    // Verificar se há referências ao Data Proxy no código gerado
    if (clientContent.includes("prisma://") || clientContent.includes("prisma+") || clientContent.includes("dataproxy")) {
      console.warn("⚠ Arquivo client.ts pode estar configurado para usar Data Proxy");
      console.warn("Regenerando Prisma Client sem Data Proxy...");
      
      // Limpar e regenerar novamente
      fs.rmSync(generatedPrismaPath, { recursive: true, force: true });
      fs.mkdirSync(generatedPrismaPath, { recursive: true });
      
      const env = {
        ...process.env,
        PRISMA_GENERATE_DATAPROXY: "false",
        PRISMA_CLIENT_ENGINE_TYPE: "library",
      };
      delete env.PRISMA_CLI_QUERY_ENGINE_TYPE;
      delete env.PRISMA_CLIENT_DATAPROXY_URL;
      delete env.DATAPROXY_URL;
      
      execSync("npx prisma generate", {
        cwd: projectRoot,
        stdio: "inherit",
        env: env,
      });
      console.log("✓ Prisma Client regenerado sem Data Proxy");
    }
  } catch (error) {
    console.warn("⚠ Não foi possível verificar o conteúdo do client.ts:", error.message);
  }
}

if (!clientExists) {
  console.warn("⚠ Arquivo client.ts não encontrado após prisma generate");
  console.warn("Isso pode indicar um problema com a configuração do Prisma");
}

// Criar enums.ts se não existir
if (!enumsExists) {
  console.warn("⚠ Arquivo enums.ts não encontrado, criando...");
  
  const enumsContent = `/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  ESTABLISHMENT: 'ESTABLISHMENT',
  MOTOBOY: 'MOTOBOY'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const EstablishmentPlan = {
  BASIC: 'BASIC',
  PROFESSIONAL: 'PROFESSIONAL'
} as const

export type EstablishmentPlan = (typeof EstablishmentPlan)[keyof typeof EstablishmentPlan]


export const DeliveryStatus = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
} as const

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus]


export const AssignmentStatus = {
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
} as const

export type AssignmentStatus = (typeof AssignmentStatus)[keyof typeof AssignmentStatus]
`;

  try {
    fs.writeFileSync(enumsFile, enumsContent, "utf8");
    console.log("✓ Arquivo enums.ts criado");
  } catch (error) {
    console.error("❌ Erro ao criar enums.ts:", error.message);
    process.exit(1);
  }
}

// Verificar novamente após criar enums.ts
if (!fs.existsSync(enumsFile)) {
  console.error("❌ Arquivo enums.ts ainda não existe após tentativa de criação");
  process.exit(1);
}

console.log("✓ Verificação concluída");
console.log(`  - Diretório: ${generatedPrismaPath}`);
console.log(`  - enums.ts: ${fs.existsSync(enumsFile) ? "✓" : "✗"}`);
console.log(`  - client.ts: ${fs.existsSync(clientFile) ? "✓" : "⚠ (pode não ser necessário se usar @prisma/client)"}`);

// Se client.ts não existir mas enums.ts existir, podemos continuar
// porque alguns setups do Prisma podem não gerar client.ts quando há output customizado
if (!clientExists && enumsExists) {
  console.warn("⚠ client.ts não encontrado, mas enums.ts existe");
  console.warn("O build pode falhar se o código importar de @/generated/prisma/client");
}
