#!/usr/bin/env node

/**
 * Script para garantir que o Prisma Client seja gerado corretamente antes do build
 * Executa o Prisma generate e cria arquivos faltantes se necessário
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const projectRoot = path.join(__dirname, "..");
const generatedPrismaPath = path.join(projectRoot, "src", "generated", "prisma");
const enumsFile = path.join(generatedPrismaPath, "enums.ts");
const indexFile = path.join(generatedPrismaPath, "index.ts");
const schemaPath = path.join(projectRoot, "prisma", "schema.prisma");

function loadEnvFromFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  try {
    const content = fs.readFileSync(filePath, "utf8");
    const lines = content.split(/\r?\n/);
    lines.forEach((line) => {
      const match = line.match(/^\s*([^#=\s]+)\s*=\s*(.*)\s*$/);
      if (!match) return;

      const key = match[1];
      let value = match[2];

      const hashIndex = value.indexOf("#");
      if (hashIndex !== -1) {
        value = value.slice(0, hashIndex);
      }

      value = value.trim();

      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      if (!process.env[key]) {
        process.env[key] = value;
      }
    });
  } catch (error) {
    console.warn("⚠ Não foi possível carregar variáveis do .env:", error instanceof Error ? error.message : String(error));
  }
}

loadEnvFromFile(path.join(projectRoot, ".env"));

console.log("Garantindo que o Prisma Client seja gerado...");

fs.mkdirSync(generatedPrismaPath, { recursive: true });

// Executar Prisma generate explicitamente COM Data Proxy
console.log("Executando: npx prisma generate --data-proxy");
try {
  const env = {
    ...process.env,
    PRISMA_GENERATE_DATAPROXY: "true",
    PRISMA_CLIENT_USE_DATAPROXY: "true",
    PRISMA_CLIENT_DATAPROXY: "true",
  };

  if (!env.DATABASE_URL) {
    console.error("❌ DATABASE_URL não está definida. Defina uma URL de Data Proxy antes de gerar o Prisma Client.");
    process.exit(1);
  }

  execSync("npx prisma generate --data-proxy", {
    cwd: projectRoot,
    stdio: "inherit",
    env: env,
  });
  console.log("✓ Prisma generate executado com sucesso (Data Proxy)");
} catch (error) {
  console.error("⚠ Erro ao executar prisma generate:", error.message);
}

function ensureBridgeFiles() {
  const indexContent = `/* Pontes para o Prisma Client oficial. Não editar manualmente. */\nexport * from "@prisma/client";\nexport type { Prisma } from "@prisma/client";\n`;

  const enumsContent = `/* !!! This is code generated by Prisma. Do not edit directly. !!! */\n/* eslint-disable */\n// biome-ignore-all lint: generated file\n// @ts-nocheck \n/*\n* This file exports all enum related types from the schema.\n*\n* 🟢 You can import this file directly.\n*/\n\n// Re-export enums from the main Prisma client\nexport {\n  Role,\n  type Role as RoleType,\n  EstablishmentPlan,\n  type EstablishmentPlan as EstablishmentPlanType,\n  DeliveryStatus,\n  type DeliveryStatus as DeliveryStatusType,\n  AssignmentStatus,\n  type AssignmentStatus as AssignmentStatusType,\n  SubscriptionStatus,\n  type SubscriptionStatus as SubscriptionStatusType,\n} from './index';\n`;

  fs.writeFileSync(indexFile, indexContent, "utf8");
  fs.writeFileSync(enumsFile, enumsContent, "utf8");
  console.log("✓ Arquivos bridge (index.ts e enums.ts) atualizados");
}

ensureBridgeFiles();

const prismaIndexPath = path.join(projectRoot, "node_modules", "@prisma", "client", "index.js");
if (fs.existsSync(prismaIndexPath)) {
  const clientContent = fs.readFileSync(prismaIndexPath, "utf8");
  if (!clientContent.includes("runtime/data-proxy")) {
    console.warn("⚠ Não foi possível confirmar o runtime do Data Proxy em @prisma/client/index.js");
  }
}

console.log("✓ Verificação concluída");
console.log(`  - Diretório bridge: ${generatedPrismaPath}`);
console.log(`  - index.ts: ${fs.existsSync(indexFile) ? "✓" : "✗"}`);
console.log(`  - enums.ts: ${fs.existsSync(enumsFile) ? "✓" : "✗"}`);
