#!/usr/bin/env node

/**
 * Script para verificar se o Prisma Client foi gerado corretamente antes do build
 * Se enums.ts não existir, cria o arquivo baseado no schema do Prisma
 */

const fs = require("fs");
const path = require("path");

const projectRoot = path.join(__dirname, "..");
const generatedPrismaPath = path.join(projectRoot, "src", "generated", "prisma");
const enumsFile = path.join(generatedPrismaPath, "enums.ts");
const clientFile = path.join(generatedPrismaPath, "client.ts");

console.log("Verificando se o Prisma Client foi gerado corretamente...");

if (!fs.existsSync(generatedPrismaPath)) {
  console.error("❌ Diretório do Prisma Client não encontrado:", generatedPrismaPath);
  console.error("Execute: npx prisma generate");
  process.exit(1);
}

if (!fs.existsSync(clientFile)) {
  console.error("❌ Arquivo client.ts não encontrado:", clientFile);
  console.error("Execute: npx prisma generate");
  process.exit(1);
}

// Se enums.ts não existir, criar baseado nos enums do schema
if (!fs.existsSync(enumsFile)) {
  console.warn("⚠ Arquivo enums.ts não encontrado, criando arquivo baseado no schema...");
  
  // Criar o arquivo enums.ts com os enums do schema
  const enumsContent = `/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  ESTABLISHMENT: 'ESTABLISHMENT',
  MOTOBOY: 'MOTOBOY'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const EstablishmentPlan = {
  BASIC: 'BASIC',
  PROFESSIONAL: 'PROFESSIONAL'
} as const

export type EstablishmentPlan = (typeof EstablishmentPlan)[keyof typeof EstablishmentPlan]


export const DeliveryStatus = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
} as const

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus]


export const AssignmentStatus = {
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
} as const

export type AssignmentStatus = (typeof AssignmentStatus)[keyof typeof AssignmentStatus]
`;

  try {
    fs.writeFileSync(enumsFile, enumsContent, "utf8");
    console.log("✓ Arquivo enums.ts criado com sucesso");
  } catch (error) {
    console.error("❌ Erro ao criar enums.ts:", error.message);
    process.exit(1);
  }
} else {
  console.log("✓ Arquivo enums.ts encontrado");
}

console.log("✓ Prisma Client verificado/corrigido");
console.log(`  - enums.ts: ${enumsFile}`);
console.log(`  - client.ts: ${clientFile}`);



